use axum::{Router, routing::{delete, get, patch, post}};
use tower_http::limit::RequestBodyLimitLayer;

use crate::http::{
    handlers::{areas, auth, automation, commission, dashboards, devices, discovery, ecosystem, energy, entities, matter as matter_handler, mqtt as mqtt_handler, presence, scenes, scripts, system},
    middleware::{auth_middleware, cors_layer},
};
use crate::state::AppState;

/// Full router: `/api/*` prefixed routes + system routes.
pub fn build(state: AppState, cors_origins: &[String]) -> Router {
    Router::new()
        // Auth
        .route("/api/auth/status", get(auth::auth_status))
        .route("/api/auth/login", post(auth::login))
        // System
        .route("/health", get(system::health))
        .route("/status", get(system::status))
        .route("/api/backup", get(system::get_backup))
        .route("/api/restore", post(system::restore_backup))
        .route("/api/events/stream", get(system::event_stream))
        .route("/server/stop", post(system::stop_server))
        .route("/events", get(system::list_events))
        .route("/clients", get(system::list_clients))
        .route("/clients/connect", post(system::connect_client))
        .route("/clients/{client_id}/disconnect", post(system::disconnect_client))
        // Devices (prefixed)
        .route("/api/devices", get(devices::list_devices).post(devices::create_device))
        .route("/api/devices/{name}", get(devices::get_device).delete(devices::remove_device).patch(devices::update_device))
        .route("/api/devices/{name}/state", patch(devices::set_device_state))
        .route("/api/devices/{name}/brightness", patch(devices::set_device_brightness))
        .route("/api/devices/{name}/temperature", patch(devices::set_device_temperature))
        .route("/api/devices/{name}/commands", post(devices::send_device_command))
        .route("/api/devices/{name}/connect", post(devices::connect_device))
        .route("/api/devices/{name}/disconnect", post(devices::disconnect_device))
        .route("/api/devices/{name}/error", post(devices::report_device_error))
        .route("/api/devices/{name}/error/clear", post(devices::clear_device_error))
        .route("/api/devices/{name}/events", get(devices::list_device_events))
        .route("/api/devices/{name}/history", get(devices::get_device_history))
        .route("/api/devices/{name}/energy", patch(energy::update_device_energy))
        // Energy (prefixed)
        .route("/api/energy/summary", get(energy::get_energy_summary))
        // Automation (prefixed)
        .route("/api/automation/rules", get(automation::list_rules).post(automation::add_rule))
        .route("/api/automation/rules/{name}", delete(automation::remove_rule))
        .route("/api/automation/rules/{name}/toggle", post(automation::toggle_rule))
        .route("/api/automation/rules/{name}/safe-mode", post(automation::toggle_safe_mode))
        .route("/api/automation/run", post(automation::run_automation))
        .route("/api/automations/webhook/{rule_name}", post(automation::webhook_trigger))
        // Discovery (prefixed)
        .route("/api/discovery/devices", get(discovery::list_discovered))
        .route("/api/discovery/devices/add", post(discovery::add_discovered_device))
        // Ecosystem (prefixed)
        .route("/api/protocols", get(ecosystem::get_protocols))
        .route("/api/ecosystem", get(ecosystem::get_ecosystem))
        // Entities (prefixed)
        .route("/api/entities", get(entities::list_entities))
        .route("/api/entities/{entity_id}", get(entities::get_entity))
        .route("/api/devices/{name}/entities", get(entities::list_device_entities))
        // Dashboards (prefixed)
        .route("/api/dashboards", get(dashboards::list_dashboards).post(dashboards::create_dashboard))
        .route("/api/dashboards/{id}", get(dashboards::get_dashboard).delete(dashboards::delete_dashboard))
        .route("/api/dashboards/{id}/views", post(dashboards::add_view))
        .route("/api/dashboards/{id}/views/{view_id}", delete(dashboards::delete_view))
        .route("/api/dashboards/{id}/views/{view_id}/cards", post(dashboards::add_card))
        .route("/api/dashboards/{id}/views/{view_id}/cards/{card_id}", delete(dashboards::delete_card))
        // Areas (prefixed)
        .route("/api/areas", get(areas::list_areas))
        .route("/api/areas/{area_id}", get(areas::get_area))
        // MQTT status (prefixed)
        .route("/api/mqtt/status", get(mqtt_handler::get_mqtt_status))
        // Matter (prefixed)
        .route("/api/matter/status", get(matter_handler::get_matter_status))
        .route("/api/matter/devices", get(matter_handler::list_matter_devices))
        .route("/api/matter/fabrics", get(matter_handler::list_matter_fabrics))
        .route("/api/matter/commission", post(commission::start_commission))
        .route("/api/matter/commission/jobs", get(commission::list_commission_jobs))
        .route("/api/matter/commission/{job_id}", get(commission::get_commission_job))
        // Scripts (prefixed)
        .route("/api/scripts", get(scripts::list_scripts).post(scripts::create_script))
        .route("/api/scripts/{id}", get(scripts::get_script).put(scripts::update_script).delete(scripts::delete_script))
        .route("/api/scripts/{id}/run", post(scripts::run_script))
        // Presence (prefixed)
        .route("/api/presence/persons", get(presence::list_persons).post(presence::create_person))
        .route("/api/presence/persons/{id}", get(presence::get_person).delete(presence::delete_person))
        .route("/api/presence/persons/{id}/sources/{source}", patch(presence::update_source))
        // Scenes (prefixed)
        .route("/api/scenes", get(scenes::list_scenes).post(scenes::create_scene))
        .route("/api/scenes/snapshot", post(scenes::snapshot_scene))
        .route("/api/scenes/{id}", get(scenes::get_scene).put(scenes::update_scene).delete(scenes::delete_scene))
        .route("/api/scenes/{id}/apply", post(scenes::apply_scene))
        // Legacy unprefixed aliases — backward compat with tests and old ui.html
        .route("/devices", get(devices::list_devices).post(devices::create_device))
        .route("/devices/{name}", get(devices::get_device).delete(devices::remove_device).patch(devices::update_device))
        .route("/devices/{name}/state", patch(devices::set_device_state))
        .route("/devices/{name}/brightness", patch(devices::set_device_brightness))
        .route("/devices/{name}/temperature", patch(devices::set_device_temperature))
        .route("/devices/{name}/commands", post(devices::send_device_command))
        .route("/devices/{name}/connect", post(devices::connect_device))
        .route("/devices/{name}/disconnect", post(devices::disconnect_device))
        .route("/devices/{name}/error", post(devices::report_device_error))
        .route("/devices/{name}/error/clear", post(devices::clear_device_error))
        .route("/devices/{name}/events", get(devices::list_device_events))
        .route("/devices/{name}/history", get(devices::get_device_history))
        .route("/automation/rules", get(automation::list_rules).post(automation::add_rule))
        .route("/automation/rules/{name}", delete(automation::remove_rule))
        .route("/automation/rules/{name}/toggle", post(automation::toggle_rule))
        .route("/automation/rules/{name}/safe-mode", post(automation::toggle_safe_mode))
        .route("/automation/run", post(automation::run_automation))
        .route("/automations/webhook/{rule_name}", post(automation::webhook_trigger))
        .route("/discovery/devices", get(discovery::list_discovered))
        .route("/discovery/devices/add", post(discovery::add_discovered_device))
        .route("/protocols", get(ecosystem::get_protocols))
        .route("/ecosystem", get(ecosystem::get_ecosystem))
        .route("/entities", get(entities::list_entities))
        .route("/areas", get(areas::list_areas))
        .route("/areas/{area_id}", get(areas::get_area))
        // Scripts legacy aliases
        .route("/scripts", get(scripts::list_scripts).post(scripts::create_script))
        .route("/scripts/{id}", get(scripts::get_script).put(scripts::update_script).delete(scripts::delete_script))
        .route("/scripts/{id}/run", post(scripts::run_script))
        // Presence legacy aliases
        .route("/presence/persons", get(presence::list_persons).post(presence::create_person))
        .route("/presence/persons/{id}", get(presence::get_person).delete(presence::delete_person))
        .route("/presence/persons/{id}/sources/{source}", patch(presence::update_source))
        // Scenes legacy aliases
        .route("/scenes", get(scenes::list_scenes).post(scenes::create_scene))
        .route("/scenes/snapshot", post(scenes::snapshot_scene))
        .route("/scenes/{id}", get(scenes::get_scene).put(scenes::update_scene).delete(scenes::delete_scene))
        .route("/scenes/{id}/apply", post(scenes::apply_scene))
        .route("/mqtt/status", get(mqtt_handler::get_mqtt_status))
        .route("/matter/status", get(matter_handler::get_matter_status))
        .route("/matter/devices", get(matter_handler::list_matter_devices))
        .route("/matter/fabrics", get(matter_handler::list_matter_fabrics))
        .route("/matter/commission", post(commission::start_commission))
        .route("/matter/commission/jobs", get(commission::list_commission_jobs))
        .route("/matter/commission/{job_id}", get(commission::get_commission_job))
        .layer(RequestBodyLimitLayer::new(64 * 1024))
        .layer(axum::middleware::from_fn_with_state(state.clone(), auth_middleware))
        .layer(cors_layer(cors_origins))
        .with_state(state)
}

/// Alias kept for test compatibility.
pub fn build_with_legacy_routes(state: AppState, cors_origins: &[String]) -> Router {
    build(state, cors_origins)
}
