use std::collections::{HashMap, VecDeque};
use std::sync::Arc;

use rumqttc::AsyncClient;
use sqlx::PgPool;
use tokio::sync::{Mutex, RwLock, broadcast, oneshot};

use crate::domain::{AutomationEngine, SmartHome};
use crate::domain::dashboard::DashboardRegistry;
use crate::domain::presence::PresenceRegistry;
use crate::domain::scene::SceneRegistry;
use crate::domain::script::ScriptRegistry;
use crate::domain::device::HistoryEntry;
use crate::http::types::{ClientSession, ServerEvent};
use crate::infrastructure::{matter::{self, CommissionStore}, mdns, mqtt};

/// Maximum number of server events retained in memory.
pub const MAX_EVENTS: usize = 1000;

/// Broadcast channel capacity for SSE fan-out.
pub const SSE_CHANNEL_CAPACITY: usize = 128;

/// Maximum number of history entries retained per device.
pub const MAX_HISTORY_PER_DEVICE: usize = 500;

#[derive(Clone)]
pub struct AppState {
    pub home: Arc<RwLock<SmartHome>>,
    pub automation: Arc<RwLock<AutomationEngine>>,
    pub events: Arc<RwLock<VecDeque<ServerEvent>>>,
    pub clients: Arc<RwLock<HashMap<String, ClientSession>>>,
    pub shutdown_tx: Arc<Mutex<Option<oneshot::Sender<()>>>>,
    /// PostgreSQL pool; `None` when the server runs without a database URL.
    pub db: Option<PgPool>,
    /// Live mDNS-discovered devices on the local network.
    pub discovery: mdns::DiscoveryStore,
    /// Optional admin token. When `None`, privileged endpoints return 403.
    pub admin_token: Option<String>,
    /// Optional API key. When `Some`, all write (non-GET/OPTIONS) requests must present it.
    pub api_key: Option<String>,
    /// MQTT connection status — updated by the subscriber loop.
    pub mqtt_status: mqtt::MqttStatusStore,
    /// MQTT async client for publishing commands; `None` when MQTT is not configured.
    pub mqtt_client: Option<AsyncClient>,
    /// Matter scanner status — updated by the Matter mDNS scanner thread.
    pub matter_status: matter::MatterStatusStore,
    /// Active and recent Matter commissioning jobs.
    pub commission_jobs: CommissionStore,
    /// Named scripts registry.
    pub scripts: Arc<RwLock<ScriptRegistry>>,
    /// Named scenes registry.
    pub scenes: Arc<RwLock<SceneRegistry>>,
    /// Presence registry (tracked persons).
    pub presence: Arc<RwLock<PresenceRegistry>>,
    /// Dashboard registry (Lovelace-style views and cards).
    pub dashboard: Arc<RwLock<DashboardRegistry>>,
    /// Broadcast sender for SSE fan-out to connected clients.
    pub events_tx: broadcast::Sender<ServerEvent>,
    /// Per-device state-change history (ring buffer, max MAX_HISTORY_PER_DEVICE entries).
    pub history: Arc<RwLock<HashMap<String, VecDeque<HistoryEntry>>>>,
    /// SHA-256 hex digest of SMART_HOME_PIN; `None` when PIN auth is not configured.
    pub pin_hash: Option<String>,
    /// Current valid session token generated by POST /api/auth/login.
    /// Replaced on each successful login. `None` until first login.
    pub session_token: Arc<Mutex<Option<String>>>,
}

impl AppState {
    pub fn new(shutdown_tx: Option<oneshot::Sender<()>>) -> Self {
        Self {
            home: Arc::new(RwLock::new(SmartHome::new())),
            automation: Arc::new(RwLock::new(AutomationEngine::new())),
            events: Arc::new(RwLock::new(VecDeque::new())),
            clients: Arc::new(RwLock::new(HashMap::new())),
            shutdown_tx: Arc::new(Mutex::new(shutdown_tx)),
            db: None,
            discovery: mdns::new_store(),
            admin_token: None,
            api_key: None,
            mqtt_status: mqtt::new_status_store(),
            mqtt_client: None,
            matter_status: matter::new_status_store(),
            commission_jobs: Arc::new(tokio::sync::RwLock::new(std::collections::HashMap::new())),
            scripts: Arc::new(RwLock::new(ScriptRegistry::new())),
            scenes: Arc::new(RwLock::new(SceneRegistry::new())),
            presence: Arc::new(RwLock::new(PresenceRegistry::new())),
            dashboard: Arc::new(RwLock::new(DashboardRegistry::new())),
            events_tx: broadcast::channel(SSE_CHANNEL_CAPACITY).0,
            history: Arc::new(RwLock::new(HashMap::new())),
            pin_hash: None,
            session_token: Arc::new(Mutex::new(None)),
        }
    }
}
